# Generated by Django 5.2 on 2025-08-27 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва проєкту')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='portfolio_screenshots/', verbose_name='Скріншот')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Посилання')),
                ('file', models.FileField(blank=True, null=True, upload_to='portfolio_files/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Проєкт портфоліо',
                'verbose_name_plural': 'Проєкти портфоліо',
            },
        ),
    ]
