# Generated by Django 5.2 on 2025-08-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публічний проєкт'),
        ),
    ]
